<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>republic</groupId>
	<artifactId>republic</artifactId>
	<packaging>jar</packaging>
	<version>0.6.4</version>
	<name>Republic</name>
	<url>http://www.polonious.com.au</url>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
	      <groupId>castor</groupId>
	      <artifactId>castor</artifactId>
			<version>0.9.5.3</version>
		</dependency>
		<dependency>
			<groupId>xerces</groupId>
			<artifactId>xercesImpl</artifactId>
			<version>2.6.2</version>
		</dependency>
		<dependency>
			<groupId>xerces</groupId>
			<artifactId>xmlParserAPIs</artifactId>
			<version>2.2.1</version>
		</dependency>
		<dependency>
			<groupId>jdom</groupId>
			<artifactId>jdom</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>jaxen</groupId>
			<artifactId>jaxen</artifactId>
			<version>1.1-beta-8</version>
		</dependency>
	</dependencies>
	<build>
    <defaultGoal>package</defaultGoal>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
            <excludes>
                 <exclude>**/*Test*.java</exclude>
            </excludes>
            </configuration>
        </plugin>
    </plugins>
	<resources>
      <resource>
        <directory>src/main/java</directory>
        <includes>
          <include>**/ParseParametersMapping.xml</include>
          <include>**/template.ods</include>
        </includes>
      </resource>
	</resources>
   </build>
</project>
