- hosts: all

  roles:
    - .ansible-galaxy-roles/ansible-set-proxy-from-env
    - .ansible-galaxy-roles/ansible-clone-env-vars

  tasks:
    - name: Run as root
      become: true
      become_user: root
      block:
        - name: Ensure a locale exists
          locale_gen:
            name: en_AU.UTF-8
            state: present

        - name: Install apt packages
          apt:
            update_cache: yes
            name: "{{ packages }}"
          vars:
            packages:
              - git
              - unzip
              - openjdk-7-jdk
              - maven
